/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BytLosenordRouteImport } from './routes/byt-losenord'
import { Route as KommerSenareRouteImport } from './routes/kommer-senare'
import { Route as LaddaNedDataRouteImport } from './routes/ladda-ned-data'
import { Route as OmRouteImport } from './routes/om'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as AdminDatakallorIndexRouteImport } from './routes/admin.datakallor.index'
import { Route as AdminDatakallorSourceIdRouteImport } from './routes/admin.datakallor.$sourceId'
import { Route as OmradenAreaIndexRouteImport } from './routes/omraden.$area.index'
import { Route as OmradenAreaTopicRouteImport } from './routes/omraden.$area.$topic'
import { Route as ApiPublicJobsEtlNoChangeRouteImport } from './routes/api/public/jobs/etl-no-change'
import { Route as ApiPublicJobsEtlStateRouteImport } from './routes/api/public/jobs/etl-state'
import { Route as ApiPublicJobsPublishIndicatorRouteImport } from './routes/api/public/jobs/publish-indicator'
import { Route as ApiPublicJobsSourceStateRouteImport } from './routes/api/public/jobs/source-state'
import { Route as ApiPublicJobsEtlBatchAbortRouteImport } from './routes/api/public/jobs/etl-batch/abort'
import { Route as ApiPublicJobsEtlBatchChunkRouteImport } from './routes/api/public/jobs/etl-batch/chunk'
import { Route as ApiPublicJobsEtlBatchCleanupFailedRouteImport } from './routes/api/public/jobs/etl-batch/cleanup-failed'
import { Route as ApiPublicJobsEtlBatchResumeHistoryRouteImport } from './routes/api/public/jobs/etl-batch/resume-history'
import { Route as ApiPublicJobsEtlBatchFinalizeRouteImport } from './routes/api/public/jobs/etl-batch/finalize'
import { Route as ApiPublicJobsEtlBatchStartRouteImport } from './routes/api/public/jobs/etl-batch/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BytLosenordRoute = BytLosenordRouteImport.update({
  id: '/byt-losenord',
  path: '/byt-losenord',
  getParentRoute: () => rootRouteImport,
} as any)
const KommerSenareRoute = KommerSenareRouteImport.update({
  id: '/kommer-senare',
  path: '/kommer-senare',
  getParentRoute: () => rootRouteImport,
} as any)
const LaddaNedDataRoute = LaddaNedDataRouteImport.update({
  id: '/ladda-ned-data',
  path: '/ladda-ned-data',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDatakallorIndexRoute = AdminDatakallorIndexRouteImport.update({
  id: '/admin/datakallor/',
  path: '/admin/datakallor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDatakallorSourceIdRoute = AdminDatakallorSourceIdRouteImport.update({
  id: '/admin/datakallor/$sourceId',
  path: '/admin/datakallor/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const OmradenAreaIndexRoute = OmradenAreaIndexRouteImport.update({
  id: '/omraden/$area/',
  path: '/omraden/$area/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmradenAreaTopicRoute = OmradenAreaTopicRouteImport.update({
  id: '/omraden/$area/$topic',
  path: '/omraden/$area/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsEtlNoChangeRoute =
  ApiPublicJobsEtlNoChangeRouteImport.update({
    id: '/api/public/jobs/etl-no-change',
    path: '/api/public/jobs/etl-no-change',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlStateRoute = ApiPublicJobsEtlStateRouteImport.update({
  id: '/api/public/jobs/etl-state',
  path: '/api/public/jobs/etl-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsPublishIndicatorRoute =
  ApiPublicJobsPublishIndicatorRouteImport.update({
    id: '/api/public/jobs/publish-indicator',
    path: '/api/public/jobs/publish-indicator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsSourceStateRoute =
  ApiPublicJobsSourceStateRouteImport.update({
    id: '/api/public/jobs/source-state',
    path: '/api/public/jobs/source-state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchAbortRoute =
  ApiPublicJobsEtlBatchAbortRouteImport.update({
    id: '/api/public/jobs/etl-batch/abort',
    path: '/api/public/jobs/etl-batch/abort',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchChunkRoute =
  ApiPublicJobsEtlBatchChunkRouteImport.update({
    id: '/api/public/jobs/etl-batch/chunk',
    path: '/api/public/jobs/etl-batch/chunk',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchCleanupFailedRoute =
  ApiPublicJobsEtlBatchCleanupFailedRouteImport.update({
    id: '/api/public/jobs/etl-batch/cleanup-failed',
    path: '/api/public/jobs/etl-batch/cleanup-failed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchResumeHistoryRoute =
  ApiPublicJobsEtlBatchResumeHistoryRouteImport.update({
    id: '/api/public/jobs/etl-batch/resume-history',
    path: '/api/public/jobs/etl-batch/resume-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchFinalizeRoute =
  ApiPublicJobsEtlBatchFinalizeRouteImport.update({
    id: '/api/public/jobs/etl-batch/finalize',
    path: '/api/public/jobs/etl-batch/finalize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchStartRoute =
  ApiPublicJobsEtlBatchStartRouteImport.update({
    id: '/api/public/jobs/etl-batch/start',
    path: '/api/public/jobs/etl-batch/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/byt-losenord': typeof BytLosenordRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/ladda-ned-data': typeof LaddaNedDataRoute
  '/om': typeof OmRoute
  '/reset-password': typeof ResetPasswordRoute
  '/statistik': typeof StatistikRoute
  '/admin/datakallor/$sourceId': typeof AdminDatakallorSourceIdRoute
  '/omraden/$area/$topic': typeof OmradenAreaTopicRoute
  '/admin/datakallor/': typeof AdminDatakallorIndexRoute
  '/omraden/$area/': typeof OmradenAreaIndexRoute
  '/api/public/jobs/etl-no-change': typeof ApiPublicJobsEtlNoChangeRoute
  '/api/public/jobs/etl-state': typeof ApiPublicJobsEtlStateRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
  '/api/public/jobs/source-state': typeof ApiPublicJobsSourceStateRoute
  '/api/public/jobs/etl-batch/abort': typeof ApiPublicJobsEtlBatchAbortRoute
  '/api/public/jobs/etl-batch/chunk': typeof ApiPublicJobsEtlBatchChunkRoute
  '/api/public/jobs/etl-batch/cleanup-failed': typeof ApiPublicJobsEtlBatchCleanupFailedRoute
  '/api/public/jobs/etl-batch/resume-history': typeof ApiPublicJobsEtlBatchResumeHistoryRoute
  '/api/public/jobs/etl-batch/resume-history': typeof ApiPublicJobsEtlBatchResumeHistoryRoute
  '/api/public/jobs/etl-batch/resume-history': typeof ApiPublicJobsEtlBatchResumeHistoryRoute
  '/api/public/jobs/etl-batch/finalize': typeof ApiPublicJobsEtlBatchFinalizeRoute
  '/api/public/jobs/etl-batch/start': typeof ApiPublicJobsEtlBatchStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/byt-losenord': typeof BytLosenordRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/ladda-ned-data': typeof LaddaNedDataRoute
  '/om': typeof OmRoute
  '/reset-password': typeof ResetPasswordRoute
  '/statistik': typeof StatistikRoute
  '/admin/datakallor/$sourceId': typeof AdminDatakallorSourceIdRoute
  '/omraden/$area/$topic': typeof OmradenAreaTopicRoute
  '/admin/datakallor': typeof AdminDatakallorIndexRoute
  '/omraden/$area': typeof OmradenAreaIndexRoute
  '/api/public/jobs/etl-no-change': typeof ApiPublicJobsEtlNoChangeRoute
  '/api/public/jobs/etl-state': typeof ApiPublicJobsEtlStateRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
  '/api/public/jobs/source-state': typeof ApiPublicJobsSourceStateRoute
  '/api/public/jobs/etl-batch/abort': typeof ApiPublicJobsEtlBatchAbortRoute
  '/api/public/jobs/etl-batch/chunk': typeof ApiPublicJobsEtlBatchChunkRoute
  '/api/public/jobs/etl-batch/cleanup-failed': typeof ApiPublicJobsEtlBatchCleanupFailedRoute
  '/api/public/jobs/etl-batch/finalize': typeof ApiPublicJobsEtlBatchFinalizeRoute
  '/api/public/jobs/etl-batch/start': typeof ApiPublicJobsEtlBatchStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/byt-losenord': typeof BytLosenordRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/ladda-ned-data': typeof LaddaNedDataRoute
  '/om': typeof OmRoute
  '/reset-password': typeof ResetPasswordRoute
  '/statistik': typeof StatistikRoute
  '/admin/datakallor/$sourceId': typeof AdminDatakallorSourceIdRoute
  '/omraden/$area/$topic': typeof OmradenAreaTopicRoute
  '/admin/datakallor/': typeof AdminDatakallorIndexRoute
  '/omraden/$area/': typeof OmradenAreaIndexRoute
  '/api/public/jobs/etl-no-change': typeof ApiPublicJobsEtlNoChangeRoute
  '/api/public/jobs/etl-state': typeof ApiPublicJobsEtlStateRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
  '/api/public/jobs/source-state': typeof ApiPublicJobsSourceStateRoute
  '/api/public/jobs/etl-batch/abort': typeof ApiPublicJobsEtlBatchAbortRoute
  '/api/public/jobs/etl-batch/chunk': typeof ApiPublicJobsEtlBatchChunkRoute
  '/api/public/jobs/etl-batch/cleanup-failed': typeof ApiPublicJobsEtlBatchCleanupFailedRoute
  '/api/public/jobs/etl-batch/finalize': typeof ApiPublicJobsEtlBatchFinalizeRoute
  '/api/public/jobs/etl-batch/start': typeof ApiPublicJobsEtlBatchStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/byt-losenord'
    | '/kommer-senare'
    | '/ladda-ned-data'
    | '/om'
    | '/reset-password'
    | '/statistik'
    | '/admin/datakallor/$sourceId'
    | '/omraden/$area/$topic'
    | '/admin/datakallor/'
    | '/omraden/$area/'
    | '/api/public/jobs/etl-no-change'
    | '/api/public/jobs/etl-state'
    | '/api/public/jobs/publish-indicator'
    | '/api/public/jobs/source-state'
    | '/api/public/jobs/etl-batch/abort'
    | '/api/public/jobs/etl-batch/chunk'
    | '/api/public/jobs/etl-batch/cleanup-failed'
    | '/api/public/jobs/etl-batch/resume-history'
    | '/api/public/jobs/etl-batch/finalize'
    | '/api/public/jobs/etl-batch/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/byt-losenord'
    | '/kommer-senare'
    | '/ladda-ned-data'
    | '/om'
    | '/reset-password'
    | '/statistik'
    | '/admin/datakallor/$sourceId'
    | '/omraden/$area/$topic'
    | '/admin/datakallor'
    | '/omraden/$area'
    | '/api/public/jobs/etl-no-change'
    | '/api/public/jobs/etl-state'
    | '/api/public/jobs/publish-indicator'
    | '/api/public/jobs/source-state'
    | '/api/public/jobs/etl-batch/abort'
    | '/api/public/jobs/etl-batch/chunk'
    | '/api/public/jobs/etl-batch/cleanup-failed'
    | '/api/public/jobs/etl-batch/resume-history'
    | '/api/public/jobs/etl-batch/finalize'
    | '/api/public/jobs/etl-batch/start'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/byt-losenord'
    | '/kommer-senare'
    | '/ladda-ned-data'
    | '/om'
    | '/reset-password'
    | '/statistik'
    | '/admin/datakallor/$sourceId'
    | '/omraden/$area/$topic'
    | '/admin/datakallor/'
    | '/omraden/$area/'
    | '/api/public/jobs/etl-no-change'
    | '/api/public/jobs/etl-state'
    | '/api/public/jobs/publish-indicator'
    | '/api/public/jobs/source-state'
    | '/api/public/jobs/etl-batch/abort'
    | '/api/public/jobs/etl-batch/chunk'
    | '/api/public/jobs/etl-batch/cleanup-failed'
    | '/api/public/jobs/etl-batch/resume-history'
    | '/api/public/jobs/etl-batch/finalize'
    | '/api/public/jobs/etl-batch/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BytLosenordRoute: typeof BytLosenordRoute
  KommerSenareRoute: typeof KommerSenareRoute
  LaddaNedDataRoute: typeof LaddaNedDataRoute
  OmRoute: typeof OmRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatistikRoute: typeof StatistikRoute
  AdminDatakallorSourceIdRoute: typeof AdminDatakallorSourceIdRoute
  OmradenAreaTopicRoute: typeof OmradenAreaTopicRoute
  AdminDatakallorIndexRoute: typeof AdminDatakallorIndexRoute
  OmradenAreaIndexRoute: typeof OmradenAreaIndexRoute
  ApiPublicJobsEtlNoChangeRoute: typeof ApiPublicJobsEtlNoChangeRoute
  ApiPublicJobsEtlStateRoute: typeof ApiPublicJobsEtlStateRoute
  ApiPublicJobsPublishIndicatorRoute: typeof ApiPublicJobsPublishIndicatorRoute
  ApiPublicJobsSourceStateRoute: typeof ApiPublicJobsSourceStateRoute
  ApiPublicJobsEtlBatchAbortRoute: typeof ApiPublicJobsEtlBatchAbortRoute
  ApiPublicJobsEtlBatchChunkRoute: typeof ApiPublicJobsEtlBatchChunkRoute
  ApiPublicJobsEtlBatchCleanupFailedRoute: typeof ApiPublicJobsEtlBatchCleanupFailedRoute
  ApiPublicJobsEtlBatchResumeHistoryRoute: typeof ApiPublicJobsEtlBatchResumeHistoryRoute
  ApiPublicJobsEtlBatchFinalizeRoute: typeof ApiPublicJobsEtlBatchFinalizeRoute
  ApiPublicJobsEtlBatchStartRoute: typeof ApiPublicJobsEtlBatchStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/byt-losenord': {
      id: '/byt-losenord'
      path: '/byt-losenord'
      fullPath: '/byt-losenord'
      preLoaderRoute: typeof BytLosenordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommer-senare': {
      id: '/kommer-senare'
      path: '/kommer-senare'
      fullPath: '/kommer-senare'
      preLoaderRoute: typeof KommerSenareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladda-ned-data': {
      id: '/ladda-ned-data'
      path: '/ladda-ned-data'
      fullPath: '/ladda-ned-data'
      preLoaderRoute: typeof LaddaNedDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/datakallor/': {
      id: '/admin/datakallor/'
      path: '/admin/datakallor'
      fullPath: '/admin/datakallor/'
      preLoaderRoute: typeof AdminDatakallorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/datakallor/$sourceId': {
      id: '/admin/datakallor/$sourceId'
      path: '/admin/datakallor/$sourceId'
      fullPath: '/admin/datakallor/$sourceId'
      preLoaderRoute: typeof AdminDatakallorSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omraden/$area/': {
      id: '/omraden/$area/'
      path: '/omraden/$area'
      fullPath: '/omraden/$area/'
      preLoaderRoute: typeof OmradenAreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omraden/$area/$topic': {
      id: '/omraden/$area/$topic'
      path: '/omraden/$area/$topic'
      fullPath: '/omraden/$area/$topic'
      preLoaderRoute: typeof OmradenAreaTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-no-change': {
      id: '/api/public/jobs/etl-no-change'
      path: '/api/public/jobs/etl-no-change'
      fullPath: '/api/public/jobs/etl-no-change'
      preLoaderRoute: typeof ApiPublicJobsEtlNoChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-state': {
      id: '/api/public/jobs/etl-state'
      path: '/api/public/jobs/etl-state'
      fullPath: '/api/public/jobs/etl-state'
      preLoaderRoute: typeof ApiPublicJobsEtlStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/publish-indicator': {
      id: '/api/public/jobs/publish-indicator'
      path: '/api/public/jobs/publish-indicator'
      fullPath: '/api/public/jobs/publish-indicator'
      preLoaderRoute: typeof ApiPublicJobsPublishIndicatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/source-state': {
      id: '/api/public/jobs/source-state'
      path: '/api/public/jobs/source-state'
      fullPath: '/api/public/jobs/source-state'
      preLoaderRoute: typeof ApiPublicJobsSourceStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/abort': {
      id: '/api/public/jobs/etl-batch/abort'
      path: '/api/public/jobs/etl-batch/abort'
      fullPath: '/api/public/jobs/etl-batch/abort'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchAbortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/chunk': {
      id: '/api/public/jobs/etl-batch/chunk'
      path: '/api/public/jobs/etl-batch/chunk'
      fullPath: '/api/public/jobs/etl-batch/chunk'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/cleanup-failed': {
      id: '/api/public/jobs/etl-batch/cleanup-failed'
      path: '/api/public/jobs/etl-batch/cleanup-failed'
      fullPath: '/api/public/jobs/etl-batch/cleanup-failed'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchCleanupFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/resume-history': {
      id: '/api/public/jobs/etl-batch/resume-history'
      path: '/api/public/jobs/etl-batch/resume-history'
      fullPath: '/api/public/jobs/etl-batch/resume-history'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchResumeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/finalize': {
      id: '/api/public/jobs/etl-batch/finalize'
      path: '/api/public/jobs/etl-batch/finalize'
      fullPath: '/api/public/jobs/etl-batch/finalize'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/start': {
      id: '/api/public/jobs/etl-batch/start'
      path: '/api/public/jobs/etl-batch/start'
      fullPath: '/api/public/jobs/etl-batch/start'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BytLosenordRoute: BytLosenordRoute,
  KommerSenareRoute: KommerSenareRoute,
  LaddaNedDataRoute: LaddaNedDataRoute,
  OmRoute: OmRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatistikRoute: StatistikRoute,
  AdminDatakallorSourceIdRoute: AdminDatakallorSourceIdRoute,
  OmradenAreaTopicRoute: OmradenAreaTopicRoute,
  AdminDatakallorIndexRoute: AdminDatakallorIndexRoute,
  OmradenAreaIndexRoute: OmradenAreaIndexRoute,
  ApiPublicJobsEtlNoChangeRoute: ApiPublicJobsEtlNoChangeRoute,
  ApiPublicJobsEtlStateRoute: ApiPublicJobsEtlStateRoute,
  ApiPublicJobsPublishIndicatorRoute: ApiPublicJobsPublishIndicatorRoute,
  ApiPublicJobsSourceStateRoute: ApiPublicJobsSourceStateRoute,
  ApiPublicJobsEtlBatchAbortRoute: ApiPublicJobsEtlBatchAbortRoute,
  ApiPublicJobsEtlBatchChunkRoute: ApiPublicJobsEtlBatchChunkRoute,
  ApiPublicJobsEtlBatchCleanupFailedRoute:
    ApiPublicJobsEtlBatchCleanupFailedRoute,
  ApiPublicJobsEtlBatchResumeHistoryRoute:
    ApiPublicJobsEtlBatchResumeHistoryRoute,
  ApiPublicJobsEtlBatchFinalizeRoute: ApiPublicJobsEtlBatchFinalizeRoute,
  ApiPublicJobsEtlBatchStartRoute: ApiPublicJobsEtlBatchStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
