/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KommerSenareRouteImport } from './routes/kommer-senare'
import { Route as OmRouteImport } from './routes/om'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as ApiPublicJobsPublishIndicatorRouteImport } from './routes/api/public/jobs/publish-indicator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KommerSenareRoute = KommerSenareRouteImport.update({
  id: '/kommer-senare',
  path: '/kommer-senare',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsPublishIndicatorRoute =
  ApiPublicJobsPublishIndicatorRouteImport.update({
    id: '/api/public/jobs/publish-indicator',
    path: '/api/public/jobs/publish-indicator',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kommer-senare'
    | '/om'
    | '/statistik'
    | '/api/public/jobs/publish-indicator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kommer-senare'
    | '/om'
    | '/statistik'
    | '/api/public/jobs/publish-indicator'
  id:
    | '__root__'
    | '/'
    | '/kommer-senare'
    | '/om'
    | '/statistik'
    | '/api/public/jobs/publish-indicator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KommerSenareRoute: typeof KommerSenareRoute
  OmRoute: typeof OmRoute
  StatistikRoute: typeof StatistikRoute
  ApiPublicJobsPublishIndicatorRoute: typeof ApiPublicJobsPublishIndicatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommer-senare': {
      id: '/kommer-senare'
      path: '/kommer-senare'
      fullPath: '/kommer-senare'
      preLoaderRoute: typeof KommerSenareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/publish-indicator': {
      id: '/api/public/jobs/publish-indicator'
      path: '/api/public/jobs/publish-indicator'
      fullPath: '/api/public/jobs/publish-indicator'
      preLoaderRoute: typeof ApiPublicJobsPublishIndicatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KommerSenareRoute: KommerSenareRoute,
  OmRoute: OmRoute,
  StatistikRoute: StatistikRoute,
  ApiPublicJobsPublishIndicatorRoute: ApiPublicJobsPublishIndicatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
