/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KommerSenareRouteImport } from './routes/kommer-senare'
import { Route as OmRouteImport } from './routes/om'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as ApiPublicJobsEtlNoChangeRouteImport } from './routes/api/public/jobs/etl-no-change'
import { Route as ApiPublicJobsEtlStateRouteImport } from './routes/api/public/jobs/etl-state'
import { Route as ApiPublicJobsPublishIndicatorRouteImport } from './routes/api/public/jobs/publish-indicator'
import { Route as ApiPublicJobsSourceStateRouteImport } from './routes/api/public/jobs/source-state'
import { Route as ApiPublicJobsEtlBatchAbortRouteImport } from './routes/api/public/jobs/etl-batch/abort'
import { Route as ApiPublicJobsEtlBatchChunkRouteImport } from './routes/api/public/jobs/etl-batch/chunk'
import { Route as ApiPublicJobsEtlBatchFinalizeRouteImport } from './routes/api/public/jobs/etl-batch/finalize'
import { Route as ApiPublicJobsEtlBatchStartRouteImport } from './routes/api/public/jobs/etl-batch/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KommerSenareRoute = KommerSenareRouteImport.update({
  id: '/kommer-senare',
  path: '/kommer-senare',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsEtlNoChangeRoute =
  ApiPublicJobsEtlNoChangeRouteImport.update({
    id: '/api/public/jobs/etl-no-change',
    path: '/api/public/jobs/etl-no-change',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlStateRoute = ApiPublicJobsEtlStateRouteImport.update({
  id: '/api/public/jobs/etl-state',
  path: '/api/public/jobs/etl-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsPublishIndicatorRoute =
  ApiPublicJobsPublishIndicatorRouteImport.update({
    id: '/api/public/jobs/publish-indicator',
    path: '/api/public/jobs/publish-indicator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsSourceStateRoute =
  ApiPublicJobsSourceStateRouteImport.update({
    id: '/api/public/jobs/source-state',
    path: '/api/public/jobs/source-state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchAbortRoute =
  ApiPublicJobsEtlBatchAbortRouteImport.update({
    id: '/api/public/jobs/etl-batch/abort',
    path: '/api/public/jobs/etl-batch/abort',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchChunkRoute =
  ApiPublicJobsEtlBatchChunkRouteImport.update({
    id: '/api/public/jobs/etl-batch/chunk',
    path: '/api/public/jobs/etl-batch/chunk',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchFinalizeRoute =
  ApiPublicJobsEtlBatchFinalizeRouteImport.update({
    id: '/api/public/jobs/etl-batch/finalize',
    path: '/api/public/jobs/etl-batch/finalize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEtlBatchStartRoute =
  ApiPublicJobsEtlBatchStartRouteImport.update({
    id: '/api/public/jobs/etl-batch/start',
    path: '/api/public/jobs/etl-batch/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRoute
  '/api/public/jobs/etl-no-change': typeof ApiPublicJobsEtlNoChangeRoute
  '/api/public/jobs/etl-state': typeof ApiPublicJobsEtlStateRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
  '/api/public/jobs/source-state': typeof ApiPublicJobsSourceStateRoute
  '/api/public/jobs/etl-batch/abort': typeof ApiPublicJobsEtlBatchAbortRoute
  '/api/public/jobs/etl-batch/chunk': typeof ApiPublicJobsEtlBatchChunkRoute
  '/api/public/jobs/etl-batch/finalize': typeof ApiPublicJobsEtlBatchFinalizeRoute
  '/api/public/jobs/etl-batch/start': typeof ApiPublicJobsEtlBatchStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRoute
  '/api/public/jobs/etl-no-change': typeof ApiPublicJobsEtlNoChangeRoute
  '/api/public/jobs/etl-state': typeof ApiPublicJobsEtlStateRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
  '/api/public/jobs/source-state': typeof ApiPublicJobsSourceStateRoute
  '/api/public/jobs/etl-batch/abort': typeof ApiPublicJobsEtlBatchAbortRoute
  '/api/public/jobs/etl-batch/chunk': typeof ApiPublicJobsEtlBatchChunkRoute
  '/api/public/jobs/etl-batch/finalize': typeof ApiPublicJobsEtlBatchFinalizeRoute
  '/api/public/jobs/etl-batch/start': typeof ApiPublicJobsEtlBatchStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kommer-senare': typeof KommerSenareRoute
  '/om': typeof OmRoute
  '/statistik': typeof StatistikRoute
  '/api/public/jobs/etl-no-change': typeof ApiPublicJobsEtlNoChangeRoute
  '/api/public/jobs/etl-state': typeof ApiPublicJobsEtlStateRoute
  '/api/public/jobs/publish-indicator': typeof ApiPublicJobsPublishIndicatorRoute
  '/api/public/jobs/source-state': typeof ApiPublicJobsSourceStateRoute
  '/api/public/jobs/etl-batch/abort': typeof ApiPublicJobsEtlBatchAbortRoute
  '/api/public/jobs/etl-batch/chunk': typeof ApiPublicJobsEtlBatchChunkRoute
  '/api/public/jobs/etl-batch/finalize': typeof ApiPublicJobsEtlBatchFinalizeRoute
  '/api/public/jobs/etl-batch/start': typeof ApiPublicJobsEtlBatchStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kommer-senare'
    | '/om'
    | '/statistik'
    | '/api/public/jobs/etl-no-change'
    | '/api/public/jobs/etl-state'
    | '/api/public/jobs/publish-indicator'
    | '/api/public/jobs/source-state'
    | '/api/public/jobs/etl-batch/abort'
    | '/api/public/jobs/etl-batch/chunk'
    | '/api/public/jobs/etl-batch/finalize'
    | '/api/public/jobs/etl-batch/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kommer-senare'
    | '/om'
    | '/statistik'
    | '/api/public/jobs/etl-no-change'
    | '/api/public/jobs/etl-state'
    | '/api/public/jobs/publish-indicator'
    | '/api/public/jobs/source-state'
    | '/api/public/jobs/etl-batch/abort'
    | '/api/public/jobs/etl-batch/chunk'
    | '/api/public/jobs/etl-batch/finalize'
    | '/api/public/jobs/etl-batch/start'
  id:
    | '__root__'
    | '/'
    | '/kommer-senare'
    | '/om'
    | '/statistik'
    | '/api/public/jobs/etl-no-change'
    | '/api/public/jobs/etl-state'
    | '/api/public/jobs/publish-indicator'
    | '/api/public/jobs/source-state'
    | '/api/public/jobs/etl-batch/abort'
    | '/api/public/jobs/etl-batch/chunk'
    | '/api/public/jobs/etl-batch/finalize'
    | '/api/public/jobs/etl-batch/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KommerSenareRoute: typeof KommerSenareRoute
  OmRoute: typeof OmRoute
  StatistikRoute: typeof StatistikRoute
  ApiPublicJobsEtlNoChangeRoute: typeof ApiPublicJobsEtlNoChangeRoute
  ApiPublicJobsEtlStateRoute: typeof ApiPublicJobsEtlStateRoute
  ApiPublicJobsPublishIndicatorRoute: typeof ApiPublicJobsPublishIndicatorRoute
  ApiPublicJobsSourceStateRoute: typeof ApiPublicJobsSourceStateRoute
  ApiPublicJobsEtlBatchAbortRoute: typeof ApiPublicJobsEtlBatchAbortRoute
  ApiPublicJobsEtlBatchChunkRoute: typeof ApiPublicJobsEtlBatchChunkRoute
  ApiPublicJobsEtlBatchFinalizeRoute: typeof ApiPublicJobsEtlBatchFinalizeRoute
  ApiPublicJobsEtlBatchStartRoute: typeof ApiPublicJobsEtlBatchStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommer-senare': {
      id: '/kommer-senare'
      path: '/kommer-senare'
      fullPath: '/kommer-senare'
      preLoaderRoute: typeof KommerSenareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-no-change': {
      id: '/api/public/jobs/etl-no-change'
      path: '/api/public/jobs/etl-no-change'
      fullPath: '/api/public/jobs/etl-no-change'
      preLoaderRoute: typeof ApiPublicJobsEtlNoChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-state': {
      id: '/api/public/jobs/etl-state'
      path: '/api/public/jobs/etl-state'
      fullPath: '/api/public/jobs/etl-state'
      preLoaderRoute: typeof ApiPublicJobsEtlStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/publish-indicator': {
      id: '/api/public/jobs/publish-indicator'
      path: '/api/public/jobs/publish-indicator'
      fullPath: '/api/public/jobs/publish-indicator'
      preLoaderRoute: typeof ApiPublicJobsPublishIndicatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/source-state': {
      id: '/api/public/jobs/source-state'
      path: '/api/public/jobs/source-state'
      fullPath: '/api/public/jobs/source-state'
      preLoaderRoute: typeof ApiPublicJobsSourceStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/abort': {
      id: '/api/public/jobs/etl-batch/abort'
      path: '/api/public/jobs/etl-batch/abort'
      fullPath: '/api/public/jobs/etl-batch/abort'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchAbortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/chunk': {
      id: '/api/public/jobs/etl-batch/chunk'
      path: '/api/public/jobs/etl-batch/chunk'
      fullPath: '/api/public/jobs/etl-batch/chunk'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/finalize': {
      id: '/api/public/jobs/etl-batch/finalize'
      path: '/api/public/jobs/etl-batch/finalize'
      fullPath: '/api/public/jobs/etl-batch/finalize'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/etl-batch/start': {
      id: '/api/public/jobs/etl-batch/start'
      path: '/api/public/jobs/etl-batch/start'
      fullPath: '/api/public/jobs/etl-batch/start'
      preLoaderRoute: typeof ApiPublicJobsEtlBatchStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KommerSenareRoute: KommerSenareRoute,
  OmRoute: OmRoute,
  StatistikRoute: StatistikRoute,
  ApiPublicJobsEtlNoChangeRoute: ApiPublicJobsEtlNoChangeRoute,
  ApiPublicJobsEtlStateRoute: ApiPublicJobsEtlStateRoute,
  ApiPublicJobsPublishIndicatorRoute: ApiPublicJobsPublishIndicatorRoute,
  ApiPublicJobsSourceStateRoute: ApiPublicJobsSourceStateRoute,
  ApiPublicJobsEtlBatchAbortRoute: ApiPublicJobsEtlBatchAbortRoute,
  ApiPublicJobsEtlBatchChunkRoute: ApiPublicJobsEtlBatchChunkRoute,
  ApiPublicJobsEtlBatchFinalizeRoute: ApiPublicJobsEtlBatchFinalizeRoute,
  ApiPublicJobsEtlBatchStartRoute: ApiPublicJobsEtlBatchStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
